### ISSUE TITLE
Unable to register plugin

### ISSUE THREAD

**Issue by MaxiIsSlayy** [EnderIce2/SDR-RPC#14]
**Describe the bug**
In the latest version of SDRSharp the plugins.xml doesn't exist and when you make one it doesn't register the plugin in the app.

**To Reproduce**
1. Download the latest version of SDRSharp
2. Follow the tutorial video in the README and when you get to the step of registering the plugin the plugins.xml file is not there anymore.

**Expected behavior**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Plugin Version 1.2.0.2
 - SDR# Version:  revision 1920
 
**Plugin Log**
N/A

**Additional context**
I'd assume that the plugin needs an update to work with whatever they have changed.

**Comment by EnderIce2** [comment]
I updated the plugin, [v1.3.0.0-pre1](https://github.com/EnderIce2/SDR-RPC/releases/tag/v1.3.0.0-pre1).

**Comment by MaxiIsSlayy** [comment]
> I updated the plugin, [v1.3.0.0-pre1](https://github.com/EnderIce2/SDR-RPC/releases/tag/v1.3.0.0-pre1).

 Hey dude thank you so much! Just wondering if you could provide a new installation instruction set, is it as simple as drag and dropping and then opening SDR sharp or is there something else you have to do?
