### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by OstojaOfficial** [EnderIce2/SDR-RPC#5]
**Desktop (please complete the following information):**
 - OS: Windows 10 64-Bit
 - Plugin Version v1.0.0.1
 - SDR# Version v1.0.0.1811

**Plugin Log**
```*** Plugin Load Error - 2021-06-24 18:18:44.082
Config Key   'EnderIce2.SDRSharpPlugin.MainPlugin,C:\SDRSharp\plugins\SDR-RPC\SDR-RPC.dll'
Type         'EnderIce2.SDRSharpPlugin.MainPlugin, SDR-RPC, Version=1.0.0.1, Culture=neutral, PublicKeyToken=null'
Message      'Exception has been thrown by the target of an invocation.'
Stack Trace
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at SDRSharp.MainForm.InitializeSharpPlugins()
```

**Comment by EnderIce2** [comment]
Not sure why you got this type of exception, maybe something is broken in the code. I tried a few times to reproduce somehow this kind of problem but no luck.

**Comment by OstojaOfficial** [comment]
> 
> 
> Not sure why you got this type of exception, maybe something is broken in the code. I tried a few times to reproduce somehow this kind of problem but no luck.

I am using SDR# community package if that helps sorry I didn't say that earlier.

**Comment by EnderIce2** [comment]
Still no problems. I'm not sure how on your system is not working. Try to reinstall the Community Package.
![image](https://user-images.githubusercontent.com/38536866/123330484-bec5e780-d546-11eb-922f-aed8fee59d7b.png)

**Comment by OstojaOfficial** [comment]
I see. But since SDR# community package can have multiple instances/profiles I tried putting SDR-RPC inside plugins folder, even tried creating SDR-RPC folder for it and added the magic line to plugins.xml in bin folder. The shortcut that SDR# community package creates on desktop uses Profile1.

**Comment by OstojaOfficial** [comment]
I even tried just putting in the plugins inside bin and putting magic line inside Plugins.xml. But when I start it up by opening SDRSharp.exe directly I get this error messge on startup.
![Capture2](https://user-images.githubusercontent.com/21225822/123331982-3d6b5680-d540-11eb-831f-d731ab8eecfa.PNG)

**Comment by EnderIce2** [comment]
I see where that exception is thrown. At least, the configuration panel shows up after this warning?

**Comment by OstojaOfficial** [comment]
I think but I am not sure it works fine after that error. I this something I should be concerned about? And what can be causing the error and is there any fix for it?

**Comment by EnderIce2** [comment]
I forgot to remove the old code, use this instead and tell me if it works as it should.
[SDR-RPC (2).zip](https://github.com/EnderIce2/SDR-RPC/files/6712167/SDR-RPC.2.zip)

**Comment by OstojaOfficial** [comment]
New error on startup.
![Capture3](https://user-images.githubusercontent.com/21225822/123333865-94722b00-d542-11eb-959b-926ddc9c8749.PNG)

**Comment by EnderIce2** [comment]
Agh!!! I will give you the program debug database. Place this file in the same place where is SDR-RPC.dll. Run again and post here the screenshot with the error.
[pdb.zip](https://github.com/EnderIce2/SDR-RPC/files/6712213/pdb.zip)

**Comment by OstojaOfficial** [comment]
![Capture4](https://user-images.githubusercontent.com/21225822/123334382-4f9ac400-d543-11eb-9a9c-ca7e28668fe6.PNG)

**Comment by EnderIce2** [comment]
Ok, so this should fix everything, and sorry for keeping you busy.
[dll+pdb.zip](https://github.com/EnderIce2/SDR-RPC/files/6712247/dll%2Bpdb.zip)

**Comment by OstojaOfficial** [comment]
No errors now. Thanks.
